@startuml

title __HELPERS's Class Diagram__\n

  package  {
    package edu.uark {
      package edu.uark.dataaccess.repository {
        package edu.uark.dataaccess.repository.helpers {
          enum PostgreEquivalencyType {
            NONE
            CURRENT_DATE
            CURRENT_TIMESTAMP
            label
          }
        }
      }
    }
  }
  

  package  {
    package edu.uark {
      package edu.uark.dataaccess.repository {
        package edu.uark.dataaccess.repository.helpers {
          enum PostgreFunctionType {
            NONE
            LOWER
            UPPER
            ANY
            label
          }
        }
      }
    }
  }
  

  package  {
    package edu.uark {
      package edu.uark.dataaccess.repository {
        package edu.uark.dataaccess.repository.helpers {
          enum SQLComparisonType {
            NONE
            EQUALS
            LESS_THAN
            LESS_THAN_OR_EQUAL_TO
            GREATER_THAN
            GREATER_THAN_OR_EQUAL_TO
            NOT_EQUAL
            IS_NULL
            IS_NOT_NULL
            label
          }
        }
      }
    }
  }
  

  package  {
    package edu.uark {
      package edu.uark.dataaccess.repository {
        package edu.uark.dataaccess.repository.helpers {
          enum SQLConditionalType {
            NONE
            AND
            OR
            label
          }
        }
      }
    }
  }
  

  package  {
    package edu.uark {
      package edu.uark.dataaccess.repository {
        package edu.uark.dataaccess.repository.helpers {
          enum SQLSortOrder {
            ASC
            DESC
            label
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
